# ===============================
# SERVER CONFIG
# ===============================
server.port=5005

# ===============================
# MONGODB CONFIG
# ===============================
spring.data.mongodb.uri=${MONGODB_URI}

# ===============================
# JWT CONFIG
# ===============================
jwt.secret=${JWT_SECRET}
jwt.expiration=604800000

# ===============================
# GOOGLE AUTH
# ===============================
google.client.id=${GOOGLE_CLIENT_ID}

# ===============================
# CLOUDINARY
# ===============================
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# ===============================
# FRONTEND URL
# ===============================
client.url=http://localhost:5173